micronaut:
  application:
    name: studentmanagement
  server:
    port: 9191
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    schema-generate: CREATE_DROP
    dialect: MYSQL
